### ISSUE TITLE
Allow href in Links to be a string

### ISSUE THREAD

**Issue by MariaSolOs** [tatethurston/nextjs-routes#83]
Since Next allows [`href` to be a string in `Link`s](https://nextjs.org/docs/api-reference/next/link), it would be nice to also offer this more compact syntax (e.g.: Allow users to write `href="/"` instead of `href={{ pathname: '/' }}`). We can still make this typed so that only the corresponding string literals are allowed.

If this sounds like a good idea, I can create the PR with the implementation :)

**Comment by tatethurston** [comment]
Hey @MariaSolOs I had this in an early version of nextjs-routes but the TypeScript error messages had poorer DX. Any typos in routes would present an error message using the first member of the routes union rather than the most similar member. This was several months ago so if the TS inference has improved in more recent versions or if you can find a way to express the type differently that helps TS yield a better error message (maybe a conditional type with the string and object variants instead of a single union?) I’m open to it. Also happy to support this via a config option if we can’t overcome the error messaging DX.

**Comment by MariaSolOs** [comment]
@tatethurston so changing `href: RouteOrQuery;` to `href: Route["pathname"] | RouteOrQuery;` results in this error message, which I think is clear enough. What do you think?
<img width="1101" alt="image" src="https://user-images.githubusercontent.com/62502207/197362064-7b463ffc-1cc0-4aad-b36a-3d36a021a6c7.png">

**Comment by tatethurston** [comment]
Yeah that error message seems clear enough. Is it roughly similar with a a bad RouteOrQuery object?

**Comment by MariaSolOs** [comment]
Hmmm no, in that case we have the error message that you described:
<img width="962" alt="image" src="https://user-images.githubusercontent.com/62502207/197362524-a1a8c0af-5ba4-476d-8136-751c80ed0bd0.png">

However, this seems to be the case with and without my type change.

**Comment by tatethurston** [comment]
Hmm even with a route closer to a valid defined route? I wonder if we regressed with the introduction of RouteOrQuery.

**Comment by MariaSolOs** [comment]
It seems like the error always shows the same route.

Given that this regression isn't caused by my proposed change, are you okay with me continuing with the implementation, or would you like to first fix this?

I'm okay either way :)

**Comment by tatethurston** [comment]
Yes continuing with the implementation sounds great, thanks

**Comment by MariaSolOs** [comment]
Implemented in #84 :)
